# Generated by Django 2.2.5 on 2019-09-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBuddyApp', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='travelBuddyApp.User'),
        ),
    ]
